### ISSUE TITLE
Login required not working 

### ISSUE THREAD

**Issue by dungbk811** [Udhayarajan/VidSnapKit#5]
I tried with https://www.facebook.com/groups/SmartVozer/permalink/3307331622823473/?sfnsn=mo&ref=share&mibextid=VhDh1V. But It returned "Video cannot be download."

Except: return error Login required

**Comment by dungbk811** [comment]
Then I put cookie to download and got the same error. I think Parsing object has problem

**Comment by Udhayarajan** [comment]
Thanks for reporting. I will look for it surely.

**Comment by Udhayarajan** [comment]
Right now, your issue is resolved in the `2.1.0-release` check for it.
