### ISSUE TITLE
Request to add Dailymotion Downloader

### ISSUE THREAD

**Issue by nikulvaghasiya** [Udhayarajan/VidSnapKit#6]
If you add dailymotion and vimeo downloader than its great app

**Comment by Udhayarajan** [comment]
Your request is transferred to VidSnapKit (The backbone of VidSnap) and I would like to intimate you that the progress for it, is started.

**Comment by Udhayarajan** [comment]
Hey, There I would like to inform you that this Library is No longer will be active. It is now moved to [Ulimate version](https://github.com/Udhayarajan/VidSnapKit-Ultimate). In addition to it the good news is both of your requests are added. Kindly check out [VidSnap](https://github.com/Udhayarajan/VidSnap/). The newest version with those update is tagged under tag name "v5.0.0-beta". Check it out.

**Comment by Udhayarajan** [comment]
For further issue, open it in either VidSnap or Ulimate.
